spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
  hikari:
    auto-commit: false
    maximum-pool-size: 10


  flyway:
    url: ${SPRING_DATASOURCE_URL}
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    locations: classpath:db/migration